### PR TITLE
Correct Spelling and Grammar

### PR DESCRIPTION
**Pull request by cjwebb**
Also, how do you feel about the sentence...?
"Imagine if your own recommendation network could easily be expanded to include your trusted circle of contacts."

Maybe it should be "Imagine if your own recommendation network could easily be expanded to include those of your trusted circle of contacts too."

Thoughts?

### CODE REVIEW

**Comment by kings13y** [comment]
Heya,

Whatever is the most terse/snappy works for me tbh.. I'd imagine the first
pass is to get someone who doesn't know about the idea at all to read the
page and see if it makes sense and sounds like something they'd use...

Maybe there should be lines in there of 'What's in it for the recruiter...
what's in it for the recommender... what's in it for the candidate.. etc'..

Still, am thinking, let's get a few ads on there and throw it out for
feedback. Whadya reckon ?

On 4 January 2015 at 13:54, Colin J Webb notifications@github.com wrote:

> Also, how do you feel about the sentence...?
> "Imagine if your own recommendation network could easily be expanded to
> include your trusted circle of contacts."
> 
> Maybe it should be "Imagine if your own recommendation network could
> easily be expanded to include those of your trusted circle of contacts too."
> 
> ## Thoughts?
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/cjwebb/job-thingo cjwebb/spelling
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/cjwebb/job-thingo/pull/1
> Commit Summary
> - Correct Spelling and Grammar
> 
> File Changes
> - _M_ src/github.com/cjwebb/job-thingo/templates/about.tmpl
>   https://github.com/cjwebb/job-thingo/pull/1/files#diff-0 (11)
> 
> Patch Links:
> - https://github.com/cjwebb/job-thingo/pull/1.patch
> - https://github.com/cjwebb/job-thingo/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cjwebb/job-thingo/pull/1.
> 
> ---
> 
> This email has been scanned by Netintelligence
> 
> ## http://www.netintelligence.com/email

## 

_W:_ http://www.d-limitd.com
_B:_ http://scalabound.org
_T:_ http://twitter.com/kings13y
_L:_ https://www.linkedin.com/in/kingsleydavies

YM/MSNM/Hangout/Skype : kingsley.davies

**Comment by cjwebb** [comment]
Makes sense. Feedback sooner rather than later is always good. I'll merge the spelling corrections in.

**Comment by kings13y** [comment]
Cool.. Didn't want to dodge the question. I think what is there is good
enough, but could be improved upon..

I don;t think it (yet) makes the benefits of using this explicit enough..
Also, been wondering what is the money model ? a % of the referral
commission or something ? No mention of commission etc on the 'add a JD'
form either, should there be ?

Cheers!

On 4 January 2015 at 17:54, Colin J Webb notifications@github.com wrote:

> Merged #1 https://github.com/cjwebb/job-thingo/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cjwebb/job-thingo/pull/1#event-213807845.
> 
> ---
> 
> This email has been scanned by Netintelligence
> 
> ## http://www.netintelligence.com/email

## 

_W:_ http://www.d-limitd.com
_B:_ http://scalabound.org
_T:_ http://twitter.com/kings13y
_L:_ https://www.linkedin.com/in/kingsleydavies

YM/MSNM/Hangout/Skype : kingsley.davies

**Comment by cjwebb** [comment]
No, the benefits aren't really explained anywhere... and also not sure of a money model. Will need to come up with something when we send emails out.

**Pull request merged**
